### ISSUE TITLE
Change CAN motor controller status frame periods

### ISSUE THREAD

**Issue by jcopi** [Team2959/2019DeepSpaceRobotProject#12]
To reduce CAN utilization (a potential cause of our CAN issues) we should reduce the frequency that periodic status frames are sent over the bus. Talon SRX functions are described [here](http://www.ctr-electronics.com/downloads/api/cpp/html/classctre_1_1phoenix_1_1motorcontrol_1_1can_1_1_base_motor_controller.html#a9356ebc0f678baf2e62f26648c361203), Spark Max functions [here](https://www.revrobotics.com/content/sw/max/sw-docs/cpp/classrev_1_1_c_a_n_spark_max_low_level.html#a128d63d2380cce0c9940941b45c22df5).

[Information about SPARK MAX periodic status frames.](https://www.revrobotics.com/sparkmax-users-manual/#section-3-3-2-1).
[Information about TalonSRX status frames](https://phoenix-documentation.readthedocs.io/en/latest/ch18_CommonAPI.html).

Some status frames provide information that is not being used (position/velocity for followers) and can be given a very large period.

**Comment by KaiBabcock** [comment]
I don't have a computer that can code at home and I will be going to Eagle
today
